name: KBBSToper
main: mc233.fun.kbbstoper.KBBSToper
version: 3.7.3
api-version: 1.21
author:
    - Fengshuai(R_Josef)
    - mincHR549
softdepend: [PlaceholderAPI]
libraries:
    - org.jsoup:jsoup:1.17.2
    - org.bstats:bstats-bukkit:3.1.0
commands:
    kbbstoper:
        description: 'KBBSToper的主要指令.'
        aliases: [bt, poster]
        usage: |
            /bt - 打开GUI菜单
            /bt help - 显示帮助页面
            /bt binding <KLPBBS论坛ID> - 绑定论坛账号，注意这里是ID不是uid
            /bt reward - 领取奖励
            /bt testreward <奖励种类> - 测试奖励
            /bt list <页数> - 列出6天以内所有顶帖者
            /bt top - 按顶贴次数顺序列出所有顶贴者
            /bt check bbsid <论坛ID> - 查看一个论坛id的绑定者
            /bt check player <玩家ID> - 查看一个玩家绑定的论坛id
            /bt delete player <玩家ID> - 删除一个玩家的数据
            /bt reload - 重载插件
permissions:
    bbstoper.admin:
        description: '管理员权限.'
        default: 'op'
        children:
            bbstoper.testreward: true
            bbstoper.list: true
            bbstoper.top: true
            bbstoper.reload: true
            bbstoper.check: true
            bbstoper.delete: true
            bbstoper.bypassquerycooldown: true
    bbstoper.user:
        description: '用户权限.'
        default: true
        children:
            bbstoper.binding: true
            bbstoper.reward: true
    bbstoper.binding:
        description: '绑定论坛账号.'
        default: true
    bbstoper.reward:
        description: '获取顶贴奖励.'
        default: true
    bbstoper.testreward:
        description: '测试顶贴奖励.'
        default: 'op'
    bbstoper.list:
        description: '列出顶贴列表.'
        default: 'op'
    bbstoper.top:
        description: '将所有玩家按照顶贴次数排序.'
        default: 'op'
    bbstoper.bypassquerycooldown:
        description: '绕过查询冷却.'
        default: 'op'
    bbstoper.check:
        description: '检查玩家ID和论坛ID.'
        default: 'op'
    bbstoper.delete:
        description: '删除一个玩家的数据.'
        default: 'op'
    bbstoper.reload: 
        description: '重载插件.'
        default: 'op'
    
